dist: bionic
language: minimal
sudo: required
addons:
  apt:
    packages:
    - tree
    - u-boot-tools
    - coreutils
env:
- toolchain=gcc-arm-9.2-2019.12-x86_64-aarch64-none-linux-gnu toolchain_url=https://armkeil.blob.core.windows.net/developer/Files/downloads/gnu-a/9.2-2019.12/binrel CROSS_GCC=aarch64-none-linux-gnu-

before_script:
- curl -LO ${toolchain_url}/${toolchain}.tar.xz
  && tar xf ${toolchain}.tar.xz
- export PATH=$(pwd)/${toolchain}/bin:$PATH
- ${CROSS_GCC}gcc -v
script:
- make all
after_success:
- tar -cJf output/${KDIR}.tar.xz -C output Image modules.tar.xz hi3798cv200-imou-sn1.dtb
- tree -hn output
- rm -f output/Image output/modules.tar.xz output/hi3798cv200-imou-sn1.dtb
deploy:
  provider: releases
  skip_cleanup: true
  overwrite: true
  file_glob: true
  api_key:
    secure: P86hW6lHbbSsZT8yI135OXUcPQpydGUxpjFFj/5p7USyCJUjiCVtq81zdbfrYgrJhjKgVA8Ps1ahQM8YT+1vvZu/WhUEF9fSRtLfwh2MFuVvkwVnwWMMxlJYvvW8KNG54Rv3rPmSHXDHqyuQe7xgqnayqBLIXLOSTic//Zx//OP6Nq/Zf41Hrvh+qSAG2e1adbhLdg/PhnvBRWBpp+2yo/VoZ82jrF5RPR9nAGVhV8/9pDzU0kqgXjLLx7KW/vnbgVB+rflIRys+MTlahO9gHE0OyVwBUwpvxqOSvQ2Dkwv1IUHgrKbiuN1IlDUrRS2fBgs1OmSWX07k0eDXAwZMXWi1EbEqZnRT8h2qhmqgObW0ZRKTcXXqhCOr4I2ibDkQNBvE4C6A/SaHCWzEIxc3mkYSyQw5V3wrcDd0D0O5aFrXQusfr3uN+tPT+CkdvmhgWIIbzf1MEgqRMyLTamqT1cRhKo/ECzdrAjO/sQRsNh523xqLcrLQ354kcPbB18BBaXxJnci5blTDi1uoWYTyIBjoSaFoe4U1nqwTlnaaGq/5D99ZMq4y7XUUnEbgoK4j9+BEoi6vVQZshUDF4jJSFlkPUOvesOn+I1Wpc4P1oEEFOKvHFebE/wfOQgIhgqdULP5LD9w2nv4ZS9jA9pevkturvCp4PIne+28MeFfbbKM=
  file: 
    - output/*.tar.xz
  on:
    repo: hanwckf/linux-hi3798c
    tags: true

